
image: docker:latest


services:
    - docker:dind

before_script:
  - apk add py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make

  - pip3 install docker-compose

test:
  script:

    - docker-compose ps
    - echo aa
