
image: python:latest

before_script:
  - python -V  

  - pip install docker-compose


test:
  script:
    - cd app
    - ls
    - echo 'Successsaasdasdss!'
    - echo 'Successsaasdasdss!'
    - python manage.py test
