
image: python:latest
services:
    - docker:dind

before_script:
  - pip install -r requirements.txt
  - pip install docker-compose

test:
  script:
    - cd app
    - ls
    - python manage.py test
    - docker-compose ps
