
image: python:latest

before_script:
  - python -V  

  - pip install docker-compose


test:
  script:
    - cd app
    - ls
    - echo 'Successsass!'
    - docker-compose run app sh -c 'echo Succeswasssass!'
