
# image: python:latest
image: docker:latest


services:
    - docker:dind

before_script:
  - apk add py-pip python3-dev
  - docker build .
  - pip install -r requirements.txt
  - pip install docker-compose

test:
  script:
    - cd app
    - ls
    - python manage.py test
    - docker-compose ps
