
image: python:latest

before_script:
  - python -V  

  - pip install docker-compose


test:
  script:
    - systemctl status docker
    - echo 'Successsass!'
    - docker-compose run app sh -c 'echo Successsass!'
