# Generated by Django 3.2.7 on 2021-09-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210924_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_project_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_submiter',
            field=models.BooleanField(default=False),
        ),
    ]
