# Generated by Django 3.2.7 on 2021-10-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_submiter',
            new_name='is_submitter',
        ),
    ]
