# Generated by Django 3.2.7 on 2021-10-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211005_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
