# Generated by Django 3.2.7 on 2021-10-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('BUGS/ERRORS', 'Bugs/Errors')], max_length=20),
        ),
    ]
