# Generated by Django 3.2.7 on 2021-10-12 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_comments',
            field=models.ManyToManyField(through='core.Comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
