# Generated by Django 3.2.7 on 2021-10-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20211012_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_comments',
        ),
    ]
