# Generated by Django 3.2.7 on 2021-10-14 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20211014_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickethistory',
            name='properties_changed',
            field=models.CharField(default=datetime.datetime(2021, 10, 14, 23, 43, 28, 707456), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('DONE', 'Done')], max_length=20),
        ),
    ]
