# Generated by Django 3.2.7 on 2021-10-15 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ticketfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_files',
            field=models.ManyToManyField(through='core.TicketFiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
