# Generated by Django 3.2.7 on 2021-10-15 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_ticket_ticket_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_history', to='core.ticket'),
        ),
    ]
