# Generated by Django 3.2.7 on 2021-10-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_comment_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketfiles',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
