# Generated by Django 3.2.7 on 2021-10-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_ticketfiles_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_files',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_files',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
