# Generated by Django 3.2.7 on 2021-10-16 01:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20211016_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_files',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_files',
            field=models.ManyToManyField(through='core.TicketFiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketfiles',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
