# Generated by Django 3.2.7 on 2021-10-16 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20211016_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketfiles',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ticket'),
        ),
        migrations.AlterField(
            model_name='ticketfiles',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
